### ISSUE TITLE
Error in Option 2: unknown reference genomes and known phylogenetic marker

### ISSUE THREAD

**Issue by luisruis** [dr-joe-wirth/phantasm#10]
Hi Dr. Joe, I am having trouble tracking a molecular marker within a folder of genomes that I annotated. With the help of ghost, I identified putative phylogenetic markers in my genome query, that is, the output files were already generated. I wish to use the polyhydroxyalkanoate protein locus. I already verified that all the genomes of my interest have this region, but I get this error when running the command from step 3.2.

Note: If all output files were successfully generated from step 1.

Thanks for helping!!
![error_phantasm](https://github.com/dr-joe-wirth/phantasm/assets/98911334/6d16af5d-da3f-49aa-868d-1c25f958ed1b)

**Comment by dr-joe-wirth** [comment]
Hello Luis,

Looking at your screenshot, it appears that you ran your command in a different directory. In order for `phantasm refinePhylogeny` to work, you need to run the command in the same folder as `initialAnalysis`. In the screenshot, you ran the command in `~/Descargas/genomes_Caulobacter_Luis` but the folder `initialAnalysis` exists in a different folder `~/Descargas/genomes_Caulobacter_Lu...Caulibacter_XenoGI`.

Copy the genome file ilinto the same directory as the folder `initialAnalysis`, `cd` into the directory containing `initialAnalysis`, then retry the command. Let me know if this solves your issue.

**Comment by luisruis** [comment]
Hello Dr. Joe, inside the directory ~/Downloads/genomes_Caulobacter_Lu...Caulibacter_XenoGI there is the initialAnalysis folder, but even so it keeps showing me the error
![1](https://github.com/dr-joe-wirth/phantasm/assets/98911334/45db2a69-afca-4e2e-8247-17e205d14da4)

**Comment by dr-joe-wirth** [comment]
Hey Luis,

You are still not running the command inside the directory containing `initialAnalysis`. You need to run the command within the folder `~/Descargas/genomes_Caulobacter_Luis/Genome_Caulobacter_XenoGI`. In your image, you are running in `~/Descargas/genomes_Caulobacter_Luis`, which does not contain the `initialAnalysis` directory.

**Comment by luisruis** [comment]
I already found the cause of the problem, the lD reference information of the genomes in the geneinfo.txt file does not correspond to the ID of my annotated genomes, geneinfo.txt has the ID information that was identified in the Genbank from my genome entry .gbff. My annotated genomes do not have their corresponding Genbank ID, so phantom cannot recognize them in final analyses. How could I perform the final analyzes on my genomes that do not have the Genbank ID, and I only know the molecular marker? step 3.2. Option 2 doesn't seem to be the solution

**Comment by dr-joe-wirth** [comment]
If you have genomes you want to analyze with a known phylogenetic marker, then use `knownPhyloMarker`. See [option 2](https://github.com/dr-joe-wirth/phantasm/blob/master/docker_build_files/README.md#32-option-2-unknown-reference-genomes-and-known-phylogenetic-markers) in the detailed tutorial. This will take in a genome file(s) and locus tag(s) as input. It will use the locus tags to identify closely-related genomes, download some or all of those genomes, and then perform phylogenomic analyses on those genomes. Your locus tags must be inside your genomes of interest. Make sure your genomes of interest are annotated, as PHANTASM relies on the annotations to extract coding sequences.

If you already know which genomes you want to compare, then `analyzeGenomes` should be used instead ([option 3](https://github.com/dr-joe-wirth/phantasm/blob/master/docker_build_files/README.md#33-option-3-known-reference-genomes))
