### ISSUE TITLE
Error for create makeSpeciesTreeWorkDir

### ISSUE THREAD

**Issue by luisruis** [dr-joe-wirth/phantasm#11]
Hello Dr. Joe,

It's me, again. I already managed to run Option 3: known reference genomes. The program was analyzing and comparing my genomes these days, but today, almost to finish the analysis, the following error appeared:

![Sin título](https://github.com/dr-joe-wirth/phantasm/assets/98911334/0c57a052-fa22-4399-9f96-236231bc46fa)

**Comment by dr-joe-wirth** [comment]
could you please share the log file with me?

**Comment by dr-joe-wirth** [comment]
are you able to share your genomes with me? Either your outgroup is too distantly related (should not be the case if they're in the same taxonomic family), or one or more of your genomes is not annotated properly. If it was the latter, then this could be why no core genes were detected. PHANTASM relies on annotations in order to extract the coding sequences from your genomes.

**Comment by luisruis** [comment]
Sure, in this link I have the genomes annotated https://drive.google.com/file/d/1z-si-qbdZvSyy5Lq1I8_9y3nKbNDw-av/view?usp=sharing . The outgroup is to strain that´s closely related to the genomes. Thanks for your support

**Comment by luisruis** [comment]
Hello Dr. Joe. My problem tiene solution? :(

**Comment by luisruis** [comment]
Hello Dr. Joe. Does my problem have a solution? :(

**Comment by dr-joe-wirth** [comment]
Hello Luis,

I have not had a chance to investigate this problem yet. I will get back to you by the end of the week.

**Comment by dr-joe-wirth** [comment]
A quick glance at your files reveals that several of your genomes are improperly formatted:

    * Caulobacter_sp_AfrMine_TT107_68_72.gbff
    * Caulobacter_vibrioides_UBA2596.gbff
    * Caulobacter_vibrioides_GCA_951805235.gbff
    * Caulobacter_rhizosphaerae_KCTC_52515.gbff

The warnings you received was BioPython telling you that something is wrong with those files. This is likely why your run failed. Remove those genomes and try again.

**Comment by luisruis** [comment]
Hello Dr. Joe,

I already removed the genomes that biopython identified as bad annotations, but I still don't get the final files. Phantasm generates all the blast and fasta files that are obtained by comparing all the genomes with each other, but the aabrhHardCore.out file is empty. The aabrhHardCore_concatenated.afa and aabrhHardCoreFamToGeneKey.txt files that are generated in the makeSpeciesTreeworDir folder are also empty. What changes should I make?

I put the image of what appears to me after the 10,404 blast files and the 816 fasta of the genomes are generated. In total I am analyzing 102 genome annotations.

![error_phantasm](https://github.com/dr-joe-wirth/phantasm/assets/98911334/9ac48d4c-c845-4906-9a52-9320dadc5da4)

**Comment by dr-joe-wirth** [comment]
As before, please upload the log file. If `aabrhHardCore.out` is empty, then `xenoGI` (the software package used to calculate core genes) is not finding any core genes.

It is difficult to pinpoint exactly which genome(s) is causing the problem without examining the blastp tables. I recommend checking those files to find out which genome(s) lacks good hits to any other genome(s). The cut-offs are described in the publication.

In the meantime, I will reopen this issue handle this error in a way that makes it clear the set of specified genomes are incompatible with PHANTASM.
