### ISSUE TITLE
 getPhyloMarker error

### ISSUE THREAD

**Issue by bharat1912** [dr-joe-wirth/phantasm#14]
Hi Joe
Thank you putting up this resource. 

1. I have a number of genomes (.gbff) downloaded from ncbi. I have renamed the sequence with the accession GCF_000833605.1_Anoxybacillus_ayderensis.gbff one.gbff as one.gbff to avoid any future conflict with the corresponding ncbi entry

2. I ran the following:
$ sudo docker run -v $(pwd):/data jwirth/phantasm:latest phantasm getPhyloMarker -i one.gbff -e XXXXl@XXXX
[sudo] password forXXXX: 

and got the folowing error -- 
If you use this software in your research, please cite our paper:
    Automating microbial taxonomy workflows with PHANTASM: PHylogenomic
    ANalyses for the TAxonomy and Systematics of Microbes
        Joseph S. Wirth and Eliot C. Bush, 2023
        https://doi.org/10.1093/nar/gkad196

PHANTASM relies on data manually acquired from the LPSN.
    These data were last retrieved on 2023-08-22

Constructing the the query 16S rRNA fasta file ... Done.

Downloading subject sequences from NCBI ... 
    Saving bacterial 16S rRNA sequences to '/data/initialAnalysis/16S/bacteria.16SrRNA.gbff.gz'.
    Saving archaeal  16S rRNA sequences to '/data/initialAnalysis/16S/archaea.16SrRNA.gbff.gz'.
    Writing subject gbff to '/data/initialAnalysis/16S/prok.16SrRNA.gbff'.
Done.

Constructing the subject 16S rRNA fasta file ... Done.

Making blast database from '/data/initialAnalysis/16S/prok.16SrRNA.fna ... Done.

Using blastn to search for related 16S rRNA gene sequences ... Done.

Constructing taxonomy for the query genome(s) ... 
    Identifying order(s) represented in the blast results ... Done.
    Importing data from NCBI Taxonomy for 5 orders:
        Bacillales (taxid: 1385) ... Done.
        Lactobacillales (taxid: 186826) ... Done.
        Rhodospirillales (taxid: 204441) ... Done.
        Eubacteriales (taxid: 186802) ... Done.
        Thermoanaerobacterales (taxid: 68295) ... Done.
    Reconciling taxonomy with LPSN taxonomy ... Done.
    Merging multiple orders into a single taxonomy ... Done.
    Mapping blast hits onto the taxonomy ... Done.
    Importing data from NCBI Assembly ... Done.
Done.

Identifying a suitable set of whole genome sequences ... Done.
Downloading genbank files from NCBI ... Traceback (most recent call last):
  File "/phantasm/phantasm", line 69, in <module>
    getPhyloMarker(genomesL, paramO)
  File "/phantasm/PHANTASM/main.py", line 24, in getPhyloMarker
    outgroup = taxonomyWrapper(allQueryGenbanksL, paramO_1)
  File "/phantasm/PHANTASM/main.py", line 93, in taxonomyWrapper
    outgroup = xenogiInterfacer_1(taxO, allQueryGenbanksL, paramO_1)
  File "/phantasm/PHANTASM/coreGenes.py", line 38, in xenogiInterfacer_1
    outgroup:Taxonomy = downloadGbffsForRootTaxonomy(taxO, maxNumSeqs, paramsO)
  File "/phantasm/PHANTASM/downloadGbff.py", line 44, in downloadGbffsForRootTaxonomy
    __downloadGbffFromSpeciesList(speciesList, humanMapFN, gbffDir)
  File "/phantasm/PHANTASM/downloadGbff.py", line 102, in __downloadGbffFromSpeciesList
    gbffFN = __downloadGbff(taxon.assemblyFtp, gbffDir)
  File "/phantasm/PHANTASM/downloadGbff.py", line 145, in __downloadGbff
    decompressGZ(gzFileName)
  File "/phantasm/PHANTASM/utilities.py", line 1149, in decompressGZ
    shutil.copyfileobj(gzFH, gbffFH)
  File "/usr/lib/python3.10/shutil.py", line 195, in copyfileobj
    buf = fsrc_read(length)
  File "/usr/lib/python3.10/gzip.py", line 314, in read1
    return self._buffer.read1(size)
  File "/usr/lib/python3.10/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.10/gzip.py", line 496, in read
    uncompress = self._decompressor.decompress(buf, size)
zlib.error: Error -3 while decompressing data: invalid block type

3. This is a list of genomes downloaded in dir wgs:
GCF_000024285.1_ASM2428v1_genomic.gbff      GCF_008274215.1_ASM827421v1_genomic.gbff
GCF_000189775.2_ASM18977v3_genomic.gbff     GCF_008630015.1_ASM863001v1_genomic.gbff
GCF_000193495.2_ASM19349v2_genomic.gbff     GCF_014205765.1_ASM1420576v1_genomic.gbff
GCF_000374005.1_ASM37400v1_genomic.gbff     GCF_014502795.1_ASM1450279v1_genomic.gbff
GCF_000423185.1_ASM42318v1_genomic.gbff     GCF_017355985.1_ASM1735598v1_genomic.gbff
GCF_000427665.1_ASM42766v1_genomic.gbff     GCF_019134555.1_ASM1913455v1_genomic.gbff
GCF_000430685.1_ASM43068v1_genomic.gbff     GCF_026167765.1_ASM2616776v1_genomic.gbff
GCF_000430685.1_ASM43068v1_genomic.gbff.gz  GCF_029024925.1_ASM2902492v1_genomic.gbff
GCF_000963885.1_ASM96388v1_genomic.gbff     GCF_029024925.1_ASM2902492v1_genomic.gbff.gz
GCF_001543145.1_ASM154314v1_genomic.gbff    GCF_030159835.1_ASM3015983v1_genomic.gbff
GCF_002251795.1_ASM225179v1_genomic.gbff    GCF_900102465.1_IMG-taxon_2599185271_annotated_assembly_genomic.gbff
GCF_004761865.1_ASM476186v1_genomic.gbff    GCF_900129075.1_IMG-taxon_2582581265_annotated_assembly_genomic.gbff

Please let me know if there are any files that you need to assist in resolving the error.

Thanks
Bharat

**Comment by bharat1912** [comment]
Hi Joe,
1. The error I was created when I performed the following steps:
$docker pull jwirth/phantasm:latest
$mkdir ~/myworkdir
$cp one.gbff ~/myworkdir
$docker -v $(pwd):/data jwirth/phantasm:latest phantasm getPhyloMarker -i one.gbff -e xxxx@xxxxx
Error as reported in my previous email

2. However, when I ran the following steps. the error the analysis has been running since the past 8 hrs without any errors
$docker pull jwirth/phantasm:latest
$mkdir ~/myworkdir
$cp one.gbff ~/myworkdir
$cd ..
$docker -v $(pwd):/data jwirth/phantasm:latest phantasm getPhyloMarker -i myworkdir/one.gbff -e xxxx@xxxxx
In summary, I cd to the dir below my workdir and ran docker from there. 

I have checked the following dir / files
a) wgs: has 50 genome.gbff files, which include one.gfff (with a sym link one.gbff -> /data/myworkdir/one.gbff)
b) blast: is creating pairwise analysis with accession numbers renamed to genus_species_type_numbers (I am assuming using esearch)

Apologies for sending you an error report without first reviewing the readme thoroughly. I am hoping to use the other options (2 and 3) soon with additional cpu's in order to increase the speed of the analysis. 

Regards and thanks for the comprehensive creation of phantasm which will assist microbiologist in their classification and taxonomy endeavours.

**Comment by dr-joe-wirth** [comment]
I think you ran the program properly. That error happens when the connection to NCBI gets interrupted. One of the downloaded files was incomplete, so the decompression for that file failed. Sometimes NCBI just is a little fussy and closes connections before a file transfer is complete.

I'm glad you got it to work. Let me know if you run into any other problems.
