### ISSUE TITLE
 Failed SSL hello

### ISSUE THREAD

**Issue by astrodea** [dr-joe-wirth/phantasm#16]
Hello,

I have tried to run the knownPhyloMarker process with the latest version of the tool and a large number of  genetic markers, however I am receiving a new error during the blasting step:
Bio.Application.ApplicationError: Non-zero return code 255 from '/usr/bin/blastp -out /data/finalAnalysis/_temp.blastp -outfmt "6 qseqid sseqid stitle staxid sacc pident length mismatch gaps gapopen evalue bitscore" -query /data/finalAnalysis/_temp.faa -db nr -remote', message 'Error: (302.26) [blastp] SSOCK#59000[5]@130.14.29.110:443: [SOCK::Connect]  Failed SSL hello: Timeout[30.000000] {error=-26880,SSL - No data of requested type currently available on underlying transport}'

I have attached the log, however the error is not reflected there:
[phantasm.log](https://github.com/dr-joe-wirth/phantasm/files/12590338/phantasm.log)

The error has happened several times and at different times during the process so I am assuming that the problem is related to NCBI connection?

Can you please advise? 

Thanks again.

**Comment by dr-joe-wirth** [comment]
This definitely looks like an issue with NCBI or your internet connection. I have seen problems with NCBI before. Let me know if this continues to happen and I'll try to implement a bug fix for the next release. If I were you, I'd try running it again and seeing if you still get the error. NCBI just might have been fussy that particular day.

**Comment by dr-joe-wirth** [comment]
going to close this out since I did not hear back from you. Feel free to reopen if the problem persists.
