### ISSUE TITLE
Phantasm Installation which works for me

### ISSUE THREAD

**Issue by bharat1912** [dr-joe-wirth/phantasm#18]
Hi Joe, Apologies for the delay in submitting a protocol of phantasm that works for me. I have provided a detailed procedure below. 

1. Install mambaforge (for conda and mamba)   
#Download the latest mambaforge from the weblink link: https://github.com/conda-forge/miniforge/releases
I use Ubuntu and clicked on 'Mambaforge-23.3.1-1-Linux-x86_64.sh to download the latest version 30 Sept 2023)

OR 

#Download it using the following command from a terminal
$wget https://github.com/conda-forge/miniforge/releases/download/23.3.1-1/Mambaforge-23.3.1-1-Linux-x86_64.sh

#Install 
$bash Mambaforge-Linux-x86_64.sh
Note mambaforge will be installed in $HOME by default

#Start a new terminal to initiate the conda base environment. Check installation of conda and mamba
$which conda
$which mamba

2. Install py39 environment with python3.9 and activate py39 env
$mamba mamba create -n py39 -y python=3.9 pip setuptools python-devtools
$conda activate py39

3. Install the following packages from the requirements.txt file (https://github.com/dr-joe-wirth/phantasm/blob/master/requirements.txt)
$pip install scipy==1.9.3 (older version installed by Python < 3.7 is not supported) ;
$pip install Bio==1.5.2
$pip install textdistance==4.5.0
$pip install numpy==1.23.5
$pip install parasail==1.3.3
$pip install rpy2==3.5.5 (older versions installed with Python < 3.7 is not supported
$pip install pyani==0.2.12 (DO NOT INSTALL with Pip but use mamba, see below) 

4. install R and tidyverse 
$mamba install r-base r-tidyverse

#Check the R version
$R –version
   R version 4.3.1 (2023-06-16) -- "Beagle Scouts"
   Copyright (C) 2023 The R Foundation for Statistical Computing
   Platform: x86_64-conda-linux-gnu (64-bit)

#Check R library paths if you wish
$R
>.libPaths()

The R library paths will be listed: (example only)
[1] "/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.3"
[2] "/usr/local/lib/R/site-library"                 
[3] "/usr/lib/R/site-library"                       
[4] "/usr/lib/R/library"

5. Install the following R packages: (I used CRAN, Canberra, Australia)
#Install DECIPHER:
> if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
> BiocManager::install("DECIPHER")

#Install dendexend
> install.packages('dendextend')

#Install ape
> install.packages('ape')

#Install gplot
> install.packages('gplot')

6. Install dependencies:
#Install pyani:
$mamba $mamba install -c bioconda pyani

#Check location of average_nucleotide_identity.py 
$which average_nucleotide_identity.py 
It should be in $HOME/mambaforge/envs/py39/bin/average_nucleotide_identity.py

#Install FastTree
#Download and save the binaryy from http://www.microbesonline.org/fasttree/#Install
$sudo mv FastTree /usr/local/bin 

#Install iqtree
$wget https://github.com/Cibiv/IQ-TREE/releases/download/v1.6.12/iqtree-1.6.12-Linux.tar.gz
$tar -zxvf iqtree-1.6.12-Linux.tar.gz
$cd iqtree/bin
$sudo cp iqtree /usr/local/bin/

#Download muscle binary, ver5.1 and complete the following steps
$wget https://github.com/rcedgar/muscle/releases/download/5.1.0/muscle5.1.linux_intel64
$mv muscle5.1.linux_intel64 muscle
$cp muscle /usr/local/bin/ 

#mafft
$sudo apt-get install -y mafft
AND
#mv mafft to local/bin/
$sudo mv /usr/bin/mafft /usr/local/bin/

#install ncbi-blast-2.14.1+
$cd /pvol/opt/
$wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.14.1+-x64-linux.tar.gz
$tar -zxvf ncbi-blast-2.14.1+-x64-linux.tar.gz
AND add the following line to .bashrc
export PATH=$PATH:<path_to/ncbi-blast-2.14.1+/bin>

#install xenoGI
$git clone https://github.com/dr-joe-wirth/xenoGI.git
AND add the following line to .bashrc
export PATH=$PATH:<path to /xenoGI-3.1.1 dir>

7. param.py path information. Substitute $HOME. 
# specify the path to the folder containing the blast+ executables
BLASTPLUS_DIR:str = '$HOME/opt/ncbi-blast-2.14.1+/bin/'

# specify the path to the MUSCLE executable
MUSCLE_EXE:str = '/usr/local/bin/muscle'

# specify the path to the FastTree executable (FastTreeMP is acceptable)
FASTTREE_EXE:str = '/usr/local/bin/FastTreeMP'

# specify the path to the IQTree exectuable
IQTREE_EXE:str = '/usr/local/bin/iqtree'

# specify the path to the phantasm directory
PHANTASM_DIR:str = '$HOME/opt/phantasm'

# specify the path to the xenoGI v3.1.0 directory
XENOGI_DIR:str = '$HOME/opt/xenoGI-3.1.1/'

# specify the paths to each of the required lpsn csv files
# MODIFYING THIS MAY CAUSE PHANTASM TO FAIL!
import os
CSV_1:str = os.path.join(PHANTASM_DIR, 'PHANTASM', 'lpsn_data', 'speciesGenus.cs
v')
CSV_2:str = os.path.join(PHANTASM_DIR, 'PHANTASM', 'lpsn_data', 'genusParents.cs
v')
CSV_3:str = os.path.join(PHANTASM_DIR, 'PHANTASM', 'lpsn_data', 'validPhylumClas
sOrderFamily.csv')
CSV_4:str = os.path.join(PHANTASM_DIR, 'PHANTASM', 'lpsn_data', 'synonymsPhylumC
lassOrderFamily.csv')

8. Download the latest version of phantasm (ver 1.1.1) to your prefered location. I use $HoME/opt
$git clone https://github.com/dr-joe-wirth/phantasm.git

#Enter phantasm and the folder PHANTASM
$cd phantasm/PHANTASM  

#make the scripts executable (not sure if this is required but I did this anyway)
$chmod a+x 

9. Usage:
#Activate python3.9
$conda activate py39

#running the script 
$python <path to phantasm.py> analyzeGenomes -i myworkdir/ -m human_map.txt -N 20 -e XXX@gmail.com

where
	analyzeGenomes 	is the subcommand
	*-i 	myworkdir, is the directory with ONLY the gbff sequences 
	-m 	human_map.txt is the mapping text file
	-e 	is the email address
	-N 	is the numbers of threads to use (4 CPU)
	-O 	ouput folder (if not given, than the default will be written to finalAnalysis)

#Geting help:
$python <path to phantasm.py> analyzeGenomes --help

**Comment by dr-joe-wirth** [comment]
Thanks for sharing.
