### ISSUE TITLE
AttributeError(ERR 1) Taxonomy objects in the list must be at their root

### ISSUE THREAD

**Issue by thisisliuqing** [dr-joe-wirth/phantasm#7]
Phantasm is a great program for taxonomy! 
When I try to test phantasm, I got the following error. I would appreciate if you could tell me possible solutions.

Constructing the subject 16S rRNA fasta file ...Done.
Mlaking blast database from '/mnt/d/ubuntu/data/24546/initialAnalysis/16S/prok.16SrRNA.fna ... Done.
Using blastn to search for related 16S rRNA gene sequences ... Done.
Constructing taxonomy for the query genome(s)Identifying order(s) represented in the blast results ... Done.Importing data from NCBI Taxonomy for 2 orders:Burkholderiales (taxid: 80840) ... Done.Neisseriales (taxid: 206351)... Done.Reconciling taxonomy with LPSN taxonomy ...Traceback (most recent call last):

File"/mnt/d/ubuntu/soft/phantasm/phantasm.py”line 197.in <module>getPhyloMarker(gbffL, param0)File "/mnt/d/ubuntu/soft/phantasm/PHANTASM/main.py”，line 25，in getPhyloMarkeroutgroup = taxonomyWrapper(allQueryGenbanksL， param0 1)
File "/mnt/d/ubuntu/soft/phantasm/PHANTASM/main.py”， line 81，in taxonomyWrapperdir=param0 1.workdir)tax0 = constructTaxonomy(taxids.saveTax=True.
File "/mnt/d/ubuntu/soft/phantasm/PHANTASM/taxonomy/taxonomyConstruction. py. line 53. in constructlaxonomyorder.addlpsnData(lpsnD)
File "/mnt/d/ubuntu/soft/phantasm/PHANTASM/taxonomy/Taxonomy.py",File"line 2113,in addLpsnDataself.processSiblings(lpsnD)
File "/mnt/d/ubuntu/soft/phantasm/PHANTASM/taxonomy/Taxonomy.py”,line 2402，inprocessSiblingsTaxonomy.mergeMultipleRoots([parent,siblingParent]， lpsnD)
File "/mnt/d/ubuntu/soft/phantasm/PHANTASM/taxonomy/Taxonomy.py”, line 1312,in mergeMultipleRootsraise AttributeError(ERR 1)
AttributeError: Al] Taxonomy objects in the list must be at their root

**Comment by dr-joe-wirth** [comment]
Thanks for bringing this bug to my attention! User feedback is crucial for continued development. I'd like to see if I can recreate this bug. Can you please share the 16S blastn results file (`initialAnalysis/16S/query.16SrRNA.blastn`) with me? Thanks for your help.

**Comment by dr-joe-wirth** [comment]
Thanks for that, but can you please send that file as an attachment? Copying and pasting has removed important formatting that I cannot easily restore.

**Comment by thisisliuqing** [comment]
I think the problem was related to docker. I deleted docker in my computer and re-run phantasm. Now it seems OK. It's starting the next step "Mapping blast hits onto the taxonomy ..."
Thank you again for this wonderful program.

**Comment by dr-joe-wirth** [comment]
I'm glad it is working. I will still work to resolve this issue.

**Comment by thisisliuqing** [comment]
[query.16SrRNA.blastn.txt](https://github.com/dr-joe-wirth/phantasm/files/11080894/query.16SrRNA.blastn.txt)
The file was attached.

**Comment by dr-joe-wirth** [comment]
There was an issue in `PHANTASM.taxonomy.Taxonomy.__processSiblings` that will be resolved with the release of version 1.0.4. Marking this issue as closed.

**Comment by thisisliuqing** [comment]
Thank you!
