### ISSUE TITLE
Stuck in the step of "Finding missing relationships and updating the Taxonomy object"

### ISSUE THREAD

**Issue by yisuo1994** [dr-joe-wirth/phantasm#8]
INFO:__main__:/home/ycc/phantasm/phantasm.py refinePhylogeny --locus_tag JPOANJ_02130 L7829.gbff exxxx@axxxxxx.org
INFO:__main__:v1.0.4
INFO:__main__:num cpus:        16
INFO:__main__:max leaves:      30
INFO:__main__:reduce num core: True
INFO:__main__:bootstrap tree:  True
INFO:__main__:num bootstraps:  100

INFO:__main__:start refinePhylogeny

INFO:PHANTASM.findMissingNeighbors.phyloMarkerBlastRunner:Using the phylogenetic marker(s) to search for closely-related genomes ... 
INFO:PHANTASM.findMissingNeighbors.__blastPhyloMarkerSeqRecords:    Searching 122304_L7829-JPOANJ_02130 against NCBI's nr database ... 
INFO:PHANTASM.findMissingNeighbors.__blastPhyloMarkerSeqRecords:    Done.
INFO:PHANTASM.findMissingNeighbors.phyloMarkerBlastRunner:Done.

INFO:PHANTASM.findMissingNeighbors.xenogiInterfacer_2:Finding missing relatives and updating the Taxonomy object ... 
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries
CRITICAL:PHANTASM.utilities.__elink:failed to retreive the result from NCBI after 5 tries

**Comment by yisuo1994** [comment]
[initialAnalysis.zip](https://github.com/dr-joe-wirth/phantasm/files/11122137/initialAnalysis.zip)

**Comment by yisuo1994** [comment]
Thank you for your prompt reply. After multiple CRITICAL errors occur, the resources occupied by the program are released, the terminal is stuck, and CTRL+c cannot kill the thread. 

Should I keep waiting for it to end?

**Comment by dr-joe-wirth** [comment]
I would just let it keep running. When I ran that step on my machine, it took several minutes but eventually it finished. I am honestly unsure why it can't be killed wit `^ + C`. I think it has something to do with the `Bio.Entrez` package wanting to finish its http request. Identifying assemblies is also a long process that requires interfacing with NCBI databases several times.

**Comment by yisuo1994** [comment]
Okay. Thank you.

**Comment by dr-joe-wirth** [comment]
A fix to this issue will be added to the next release. Marking this issue as closed.
